import { useState } from "react";
import { Link } from "react-router-dom";

import { ExampleLoader } from "../components/ExampleLoader";
import { InputPanel } from "../components/InputPanel";
import { ResultsPanel } from "../components/ResultsPanel";
import { useAnalysis } from "../hooks/useAnalysis";

const initialForm = {
  passage: "",
  question: "",
  aiResponse: "",
};

export function AnalyzePage() {
  const [form, setForm] = useState(initialForm);
  const { status, data, error, analyze, reset } = useAnalysis();

  const handleChange = (key, value) => {
    setForm((current) => ({ ...current, [key]: value }));
  };

  const handleExample = (example) => {
    setForm(example);
    reset();
  };

  const handleReset = () => {
    setForm(initialForm);
    reset();
  };

  return (
    <div className="px-4 py-6 sm:px-6 lg:px-8">
      <div className="mx-auto flex max-w-7xl flex-col gap-6">
        <header className="panel-shell rounded-[1.5rem] px-5 py-4">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <p className="eyebrow">Analysis Workspace</p>
              <h1 className="mt-2 text-3xl font-semibold text-stone-50">
                Build the evidence packet and inspect the verdict.
              </h1>
            </div>

            <div className="flex flex-wrap gap-3">
              <Link to="/" className="secondary-cta">
                Back to Landing
              </Link>
              <button
                type="button"
                onClick={handleReset}
                className="rounded-full border border-white/15 bg-white/5 px-5 py-3 text-sm font-semibold text-stone-200 transition hover:border-white/30 hover:bg-white/10"
              >
                Reset Workspace
              </button>
            </div>
          </div>
        </header>

        <section className="panel-shell rounded-[2rem] px-6 py-8 lg:px-10">
          <div className="grid gap-4 lg:grid-cols-[1.1fr_0.9fr]">
            <div>
              <p className="eyebrow">Use The Tool</p>
              <h2 className="mt-3 text-4xl font-semibold text-stone-50">
                Submit a source, the question, and the answer under review.
              </h2>
            </div>
            <p className="max-w-xl text-sm leading-7 text-stone-300">
              This page is the working product surface. Paste your own example
              or load one of the presets, then inspect the sentence cards and
              overall verdict generated by the backend.
            </p>
          </div>
        </section>

        <div className="grid gap-6 xl:grid-cols-[1.02fr_0.98fr]">
          <section className="panel-shell rounded-[2rem] p-6 lg:p-8">
            <div className="mb-6 flex flex-col gap-4 border-b border-white/10 pb-6 sm:flex-row sm:items-end sm:justify-between">
              <div>
                <p className="eyebrow">Input Console</p>
                <h2 className="mt-2 text-3xl font-semibold text-stone-50">
                  Prepare your analysis
                </h2>
              </div>
              <p className="max-w-md text-sm leading-6 text-stone-400">
                Start with a demo or paste your own material. When you run the
                analysis, the backend scores the response sentence by sentence.
              </p>
            </div>

            <ExampleLoader onLoad={handleExample} />

            <InputPanel
              form={form}
              onChange={handleChange}
              onAnalyze={() => analyze(form)}
              onClear={handleReset}
              loading={status === "loading"}
            />

            {error ? (
              <p className="mt-4 rounded-2xl border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-200">
                {error}
              </p>
            ) : null}
          </section>

          <ResultsPanel status={status} data={data} />
        </div>
      </div>
    </div>
  );
}
